language: swift
xcode_project: SportsEvents/SportsEvents.xcodeproj # path to your xcodeproj folder
xcode_scheme: SportsEvents
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
